//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGUI_Xsd.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OGUI_Xsd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似         const std::string_view&amp; str = attr.name;
        ///        switch (attr_name_hash)
        ///        {
        ///{AllSwitchInitAttribute}
        ///            default: return false;
        ///        } 的本地化字符串。
        /// </summary>
        internal static string SwitchTemplate {
            get {
                return ResourceManager.GetString("SwitchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     void IXmlFactory_{ElementName}::Internal_Init()
        ///    {
        ///        {ParentTypeName}::Internal_Init();
        ///{AllInit}
        ///    }
        ///
        ///    bool IXmlFactory_{ElementName}::Internal_InitAttribute(size_t attr_name_hash, const XmlAttribute&amp; attr)
        ///    {
        ///        {ParentTypeName}::Internal_InitAttribute(attr_name_hash, attr);
        ///{Switch}
        ///        return false;
        ///    }
        /// 的本地化字符串。
        /// </summary>
        internal static string XmlFactoryClassCpp {
            get {
                return ResourceManager.GetString("XmlFactoryClassCpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     class {xx_API} IXmlFactory_{ElementName} : public {ParentTypeName}
        ///    {
        ///    public:
        ///{AllAttributeDefinition}
        ///
        ///        IXmlFactory_{ElementName}()
        ///        {
        ///            xml_name = &quot;{ElementName}&quot;;
        ///            xml_namespace = &quot;{Namespace}&quot;;
        ///            xml_qualified_name = &quot;{Qualified}&quot;;
        ///            {Mixed}
        ///        }
        ///
        ///        virtual bool InitAttribute(VisualElement&amp; new_element, const XmlElement&amp; Asset, CreationContext&amp; context) override;
        ///        virtual VisualElement* Create(const XmlElem [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string XmlFactoryClassH {
            get {
                return ResourceManager.GetString("XmlFactoryClassH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {Include}
        ///
        ///namespace OGUI
        ///{
        ///{Content}
        ///} 的本地化字符串。
        /// </summary>
        internal static string XmlFactoryCppFile {
            get {
                return ResourceManager.GetString("XmlFactoryCppFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #pragma once
        ///#include &lt;string&gt;
        ///#include &lt;string_view&gt;
        ///#include &lt;optional&gt;
        ///#include &lt;functional&gt;
        ///#include &quot;OpenGUI/Xml/XmlFactory.h&quot;
        ///{Include}
        ///
        ///namespace {Namespace}
        ///{
        ///	using namespace OGUI;
        ///{Content}
        ///} 的本地化字符串。
        /// </summary>
        internal static string XmlFactoryHFile {
            get {
                return ResourceManager.GetString("XmlFactoryHFile", resourceCulture);
            }
        }
    }
}
