//			name,				index,			inherited,				type,				id,							initial
//Begin Yoga props
STYLEPROP(	flex,				0,				NonInherited,			float,				"flex",						YGUndefined					)
STYLEPROP(	flexGrow,			1,				NonInherited,			float,				"flex-grow",				0.f							)
STYLEPROP(	flexShrink,			2,				NonInherited,			float,				"flow-shrink",				1.f							)
STYLEPROP(	flexBasis,			3,				NonInherited,			YGValue,			"flex-basis",				YGValueAuto					)
STYLEPROP(	left,				4,				NonInherited,			YGValue,			"left",						YGValueAuto					)
STYLEPROP(	top,				5,				NonInherited,			YGValue,			"top",						YGValueAuto					)
STYLEPROP(	right,				6,				NonInherited,			YGValue,			"right",					YGValueAuto					)
STYLEPROP(	buttom,				7,				NonInherited,			YGValue,			"buttom",					YGValueAuto					)
STYLEPROP(	marginLeft,			8,				NonInherited,			YGValue,			"margin-left",				YGValueZero					)
STYLEPROP(	marginTop,			9,				NonInherited,			YGValue,			"margin-right",				YGValueZero					)
STYLEPROP(	marginRight,		10,				NonInherited,			YGValue,			"margin-right",				YGValueZero					)
STYLEPROP(	marginButtom,		11,				NonInherited,			YGValue,			"margin-buttom",			YGValueZero					)
STYLEPROP(	paddingLeft,		12,				NonInherited,			YGValue,			"padding-left",				YGValueZero					)
STYLEPROP(	paddingTop,			13,				NonInherited,			YGValue,			"padding-top",				YGValueZero					)
STYLEPROP(	paddingRight,		14,				NonInherited,			YGValue,			"padding-right",			YGValueZero					)
STYLEPROP(	paddingButtom,		15,				NonInherited,			YGValue,			"padding-buttom",			YGValueZero					)
STYLEPROP(	borderLeftWidth,	16,				NonInherited,			float,				"border-left-width",		0.f							)
STYLEPROP(	borderTopWidth,		17,				NonInherited,			float,				"border-top-width",			0.f							)
STYLEPROP(	borderRightWidth,	18,				NonInherited,			float,				"border-right-width",		0.f							)
STYLEPROP(	borderBottomWidth,	19,				NonInherited,			float,				"border-buttom-width",		0.f							)
STYLEPROP(	width,				20,				NonInherited,			YGValue,			"width",					YGValueZero					)
STYLEPROP(	height,				21,				NonInherited,			YGValue,			"height",					YGValueZero					)
STYLEPROP(	position,			22,				NonInherited,			YGPositionType,		"position",					YGPositionTypeRelative		)
STYLEPROP(	overflow,			23,				NonInherited,			YGOverflow,			"overflow",					YGOverflowVisible			)
STYLEPROP(	alignSelf,			24,				NonInherited,			YGAlign,			"align-self",				YGAlignAuto					)
STYLEPROP(	maxWidth,			25,				NonInherited,			YGValue,			"max-width",				YGValueUndefined			)
STYLEPROP(	maxHeight,			26,				NonInherited,			YGValue,			"max-height",				YGValueUndefined			)
STYLEPROP(	minWidth,			27,				NonInherited,			YGValue,			"min-width",				YGValueAuto					)
STYLEPROP(	minHeight,			28,				NonInherited,			YGValue,			"min-height",				YGValueAuto					)
STYLEPROP(	flexDirection,		29,				NonInherited,			YGFlexDirection,	"flex-direction",			YGFlexDirectionColumn		)
STYLEPROP(	alignContent,		30,				NonInherited,			YGAlign,			"align-content",			YGAlignFlexStart			)
STYLEPROP(	alignItems,			31,				NonInherited,			YGAlign,			"align-items",				YGAlignStretch				)
STYLEPROP(	justifyContent,		32,				NonInherited,			YGJustify,			"justify-content",			YGJustifyFlexStart			)
STYLEPROP(	wrap,				33,				NonInherited,			YGWrap,				"wrap",						YGWrapNoWrap				)
STYLEPROP(	display,			34,				NonInherited,			YGDisplay,			"display",					YGDisplayFlex				)
//End Yoga props																											
//Begin draw props																											
STYLEPROP(	color,				35,				Inherited,				Color4f,			"color",					Color4f::vector_zero()		)
STYLEPROP(	fontSize,			36,				Inherited,				float,				"fontSize",					0.f							)
//End draw props